### ISSUE TITLE
Request: add hex/dec conversion for top of stack

### ISSUE THREAD

**Issue by hollie** [fastrgv/Interval-RPN-Calculator#3]
Hello Rod,

what would be a useful addition: if there would be a hotkey to convert between decimal and hexadecimal representation of the number on the top of the stack. I don't know if this is something that would be possible to add easily?

Best regards,
 Lieven.

**Comment by fastrgv** [comment]
I think it's easy.  Let me try...

**Comment by fastrgv** [comment]
I guess I don't want to open that can of worms.  You are welcome to try.
If you do I suggest letting 'h' toggle hex mode.

**Comment by fastrgv** [comment]
Lieven,
Note that if you are not specifically in need of interval output in an RPN
calculator, you really should be working with my other project "difRpn"
instead.  It runs on all 3 platforms, uses Ada only, and is simpler to
build.
Let me explain my hesitance to use Makefiles...

I dislike both Microsoft and Apple because of the freedoms they deny me,
and I fully support the F.S.F.  Thusly, I want to minimize my involvment
with their OS's.  Still, I want to reach their large audiences with my
programs.

My design goals are to A) require nothing of mere users, and B) for Ada
developers, require only that they install AdaCore on their machines.
Specifically, I do not wish to require them to install MINGW.  This means
that Windows users can't use a Makefile.

Most of my apps run on Windows, OSX, and linux.  That is my eventual plan
for IntervalRpnCalc too.  (GAOL will one day be available on Windows)

So gpr build files are fine and work on all 3 OS's, although I am more
familiar with script/bat files.

Rod

**Comment by hollie** [comment]
Hey Rod,

OK clear. I just sent you the makefile pull request because I use it in my code development. No issue if you don't want to use it! Just disregard my changes in that case.

I'll take a look at difRpn.

Have a nice day!
 Lieven.

**Comment by fastrgv** [comment]
Oh, I included it, but I also replaced my scripts too.  However, I had to
edit it slightly to work for me.  I have another Ada compiler (gnu) visible
in my path but I prefer to use the one from AdaCore.  More importantly, the
last line seemed to have been a problem on linux.  Maybe had something to
do with somehow not having a required tab.  Note I have already added a
similar but simpler Makefile to difRpn.  As I say though, this app compiles
& runs on Windows too so I need the bat files for that.  The Ada code is
very similar so I have updated it to allow extraneous (enter)-key clicks
without error, as in intRpn.
